### ISSUE TITLE
Could we hash the passwords?

### ISSUE THREAD

**Issue by nguoianphu** [sscarduzio/elasticsearch-readonlyrest-plugin#102]
Just see that Search Guad (https://github.com/floragunncom/search-guard) can hide the passwords in its hash tools. Could we do the same thing in this plugin? Or just use the md5 method...

Instead of
    `auth_key: admin:admin`

It'd be nice to
    `auth_key: admin:$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG`

**Comment by sscarduzio** [comment]
[Done.](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules#list-of-supported-rules-in-acl-blocks)
Look for `auth_key_sha1`.

I also released SSL support which can finally protect these credentials from men in the middle. I suggest using these two features together.

**Comment by nguoianphu** [comment]
Thank you! Awesome job! :+1:

**Comment by teebu** [comment]
Not sure if this is related, but when I save the auth key, user:pass, can you save it encrypted if it doesn't already?

You can see it in: `localhost/_nodes`

**Comment by sscarduzio** [comment]
Hey @teebu, good catch! Apparently that API is dumping the raw ES settings as it's parsed. 
Unfortunately the parsed configuration is an immutable object. So to remove/encrypt the credentials I'd need to go and tamper it using reflection (which is still doable).

The approach followed by Shield is to store credentials in separate "users" and "groups" files under the plugin's directory. 
But I don't really like this because it makes configuration brittle for mundane technical reasons.

Another approach can be modifying the output of that API call and remove the "readonlyrest" bit entirely.

Do you have an idea of what tools calls this endpoint?

**Comment by teebu** [comment]
No idea.
