### ISSUE TITLE
Plugin for ES 5.x support?

### ISSUE THREAD

**Issue by krisko** [sscarduzio/elasticsearch-readonlyrest-plugin#108]
Hi,
do you plan to support also elasticsearch version 5.x? Is it still possible to create such a plugin for this version?

thank you

**Comment by sscarduzio** [comment]
5.0 is not generally available yet. I had a look at porting it, it requires some work. I'll have a look into it

**Comment by Shifter2600** [comment]
I am excited about this as well. ES 5.x RC1 was just announced.

**Comment by theetete** [comment]
GA !

**Comment by sscarduzio** [comment]
Yeah cool, but porting this to 5.x is officially a [PITA](http://www.urbandictionary.com/define.php?term=pita) 😂

**Comment by sscarduzio** [comment]
Found this, adding to the records because might be helpful: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_plugins.html

**Comment by nmaisonneuve** [comment]
+1 waiting the release of this plugin to move to Es 5

**Comment by MrGarry2016** [comment]
+1

**Comment by Hacksign** [comment]
+1 need this plugin support 5.x too ;)

**Comment by sscarduzio** [comment]
Hi Guys,
I hate to say: I could do it, but as it stands, literally does not make sense for me to continue developing this software.

I left my job and I'm creating a new (unrelated) product to sustain myself in the long run. Doing it while maintaining a security plugin is very tough because this requires a lot of time and attention. 

And if I don't put all the work this plugin needs, we are all left with a half-assed security solution, which is the worse thing you could have.

Please read the [Patreon](https://www.patreon.com/readonlyrest) campaign page: it's time to take this project to the next level or close it.

The only thing to add: as I always said, PRs are even better than donations. But in the absence of PRs, contributions are vital.

Best,

_Simone

**Comment by nmaisonneuve** [comment]
@Simone I think your plugin plays a vital role in the Es eco-system because
it is a good alternative to the paid/expensive solution Shield.

I dont have time to help -> here is my modest contribution 50$  !
(and thanks again for this free plugin)


Question:
if you got quickly enough financial support,  do you have a scheduled
planning for the Es 5. support




​

**Comment by sscarduzio** [comment]
@nmaisonneuve thanks for the contribution! 
I had a cursory look at what's needed to be done, the API is very different in v5.0, I reckon it's going to take at least one week full time to make it happen + tests.

**Comment by theetete** [comment]
Hi,
I've attended yesterday Elastic 5.0 webinar, and one of the main message I got was Elastic (the company) want to push X-PACK (the commercial pack) hard. That's why x-pack is bundled by default (and may conflict with this plugin).

**Comment by sscarduzio** [comment]
@theetete what do you mean, they provide installation instructions in their docs. It means you first install ES and then x-pack (optionally).

https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html

**Comment by theetete** [comment]
My bad you re right. I got confused with with dev tools embedded in Kibana
and x pack

**Comment by nmaisonneuve** [comment]
any news about the support of v5,  a potential date for its release?

**Comment by sscarduzio** [comment]
@nmaisonneuve I've spent some time on this, here's a report:
* Plugins are forced to declare all possible YML properties they require to read: we use an unbounded list of ACL blocks, so I had to [tell ES](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/commit/a47fac52004a25af89054859775271d381c74d757) to accept the first 100 blocks and 100 groups.. Horrible hack, moving on for now.
* Each plugin lives in an isolated class loader, I cannot access Netty data structures by reflection. This is a major issue for how my plugin works.
* This [guide](http://david.pilato.fr/blog/2016/10/16/creating-a-plugin-for-elasticsearch-5-dot-0-using-maven-updated-for-ga/) offers good help until ES docs are basically zero. But this plugin can't follow this route because the netty data structures are not contained anymore in the parameters of the new plugin API.
* In the main project Netty3 transport has been isolated to a module (a sort of internal plugin) which makes me think I could release this plugin as a jar to be replaced in the $ES_HOME/modules/transport-netty3 folder. I'll have then to comply with the heavily customised gradle driven workflow in ES, which has a learning curve (moved the first steps yesterday).

Would be really helpful to see how other reflection based community plugins are approaching these issues, but I didn't find anything useful yet.

**Comment by sscarduzio** [comment]
One more update: got the official ES plugin build/test tools to work. We *might* be able to have a 5.0 version working as it was in 2.0.

**Comment by nmaisonneuve** [comment]
Great news Simone,

Let use know when you have a first version.

Thanks  !

**Comment by psaiz** [comment]
That is indeed great news! Thanks!

**Comment by aeneaswiener** [comment]
Thanks for this plugin, I am also looking forward to ES 5 support.

**Comment by sscarduzio** [comment]
A few updates on this, as it's been a long path to 5.x. 

- [x] move to ES gradle plugin `org.elasticsearch.esplugin`
- [x] comply with new settings checks
- [x] find a way to forward the HTTP level information to the upper layer (where indices info is also avaliable)
- [x] port SSL transport to Netty4
- [x] strategy to debug project from IDE
- [ ] strategy to debug project from IDE with configuration (maybe using ES integration tests)
- [ ] restore indices alias inspection (my reflection based machinery got busted in 5.x)
- [ ] restore naming conventions in the deliverable zip file
- [ ] restore package checksum calculation

**Comment by nmaisonneuve** [comment]
thanks for the update
keep going Simone !
let us know a potential release date

**Comment by sscarduzio** [comment]
https://readonlyrest.com/#download

**Comment by nmaisonneuve** [comment]
the download doesn't work for me , "error sending email "..

**Comment by nmaisonneuve** [comment]
i see a pre-release here
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/releases.
you just closed this ticket should i assume that the pre-release = the
release ?

**Comment by sscarduzio** [comment]
@nmaisonneuve yeah sorry for the unclear name, but this pre release is the port of the old logic to the new plugin API  and build/test system. I encourage you to use it, and find if there's some incompatibility.

**Comment by sscarduzio** [comment]
## NB: Enabling SSL in v5.x ReadonlyREST
You need to tell Elasticsearh to use Readonlyrest's transport (called ssl_netty4) as documented in the updated [README.md](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/README.md#use-case-0-enable)

```yml
http.type: ssl_netty4
readonlyrest:
   ...
```
