### ISSUE TITLE
Seeking kibana_index example

### ISSUE THREAD

**Issue by drakkhen** [sscarduzio/elasticsearch-readonlyrest-plugin#235]
Hello!  Is there a usage example of the `kibana_index` directive mentioned in the [Rules: Elasticsearch Level](https://readonlyrest.com/documentation/index.html#Rules--Elasticsearch_level) section of the documentation?

I'm trying to add it to a `access_control_rules` block alongside `kibana_access`, `indices`, etc. but it's giving me an unexpected error: 

```
Guice Exception: org.elasticsearch.plugin.readonlyrest.settings.SettingsMalformedException: Unknown rule name: 'kibana_index'
```

My goal is to use a different kibana_index for different users/groups so that Saved Objects are not shared among different groups.

Thank you!

**Comment by sscarduzio** [comment]
Hello @drakkhen, thank you for discovering a regression. I have now fixed it and amended the documentation too.

Later this week I will investigate if we can do more with `kibana_index` such as pass the info back to the Kibana plugin and hijack the current Kibana session to that specific kibana index.
That would be awesome because you could obtain independent dashboards  for each group or user.

**Comment by drakkhen** [comment]
Awesome -- thank you!!

Just to clarify:  is it not currently possible to provide different `kibana_index` values in each block?  For instance, in [this example in README.md](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blame/master/README.md#L104), can I specify a `kibana_index` value after the `kibana_access` lines of both ""::RW DEVELOPER::"" and ""::RO DEVELOPER::"" blocks?  (Or is that the wrong place for `kibana_index` entirely?)

**Comment by sscarduzio** [comment]
`kibana_index` is a modifier for `kibana_access`, in the sense that `kibana_access` is a macro that lets through very few (read) actions towards all indices and is a bit more permissive about the ".kibana" index (because Kibana needs to save its data, otherwise it won't work). 

The `kibana_index` modifier, used in the **same block** with `kibana_access´ informs the macro to be more permissive for another index, i.e. ".kibana_xyz" instead of ".kibana".
