### ISSUE TITLE
found 1 subrequests

### ISSUE THREAD

**Issue by krisko** [sscarduzio/elasticsearch-readonlyrest-plugin#239]
Hi,
I wonder what does this message mean:

```
[2017-06-09T14:30:38,530][INFO ][o.e.p.r.e.r.RequestContextImpl] found 1 subrequests
[2017-06-09T14:30:38,530][INFO ][o.e.p.r.e.r.SubRequestContext] id: 1134191940-1326183620-sub--1632594963 - Not replacing in sub-request. Indices are the same. Old:[.kibana] New:[.kibana]
```

This start to occur when I add indices rule to my RoR config.
Does not generate above message:

```
    - name: "::KB::"
      type: allow
      kibana_access: ro
      auth_key: user:pass
      hosts: ["127.0.0.1"]
```
Does genarete this message
```
    - name: "::KB::"
      type: allow
      kibana_access: ro
      indices: [".kibana"]
      auth_key: user:pass
      hosts: ["127.0.0.1"]
```

**Comment by sscarduzio** [comment]
Hi @krisko some requests in Elasticsearch (the ones assignable from CompositeIndicesRequest) are actually containers to 0..N subrequests. 

When any request or subrequest flows in the indices rule, this rule resolves any wildcard to concrete indices and rewrites the request to that list of indices.

The code that rewrites the indices will eventually refuse to operate any change to the request, since it was asked to change index to the existing index (".kibana" to ".kibana").

So yes, those two log lines should probably not be in INFO..
