### ISSUE TITLE
multi-tenancy

### ISSUE THREAD

**Issue by shubhamverma27** [sscarduzio/elasticsearch-readonlyrest-plugin#249]
How to implement multi tenancy?
For ex. in current implementation every user can see names of all the index patterns and All the Dasboards.
but can't open it.
I want to restrict that. I want the given user to see only those indices/dashboard which he is allowed to open.
Can it be done by having multiple .kibana config indices??and how?

**Comment by shubhamverma27** [comment]
https://github.com/wtakase/kibana-own-home will this plugin work with readonlyrest?? @sscarduzio

**Comment by sscarduzio** [comment]
I'm currently investigating this as a feature of the Kibana plugin. I never tried own home.

**Comment by ld57** [comment]
mmh an idea @sscarduzio :
what about link users to a RoR group, and just use a dedicated kibana indice like : 
.kinana-{group}

all vizu, dash and co are stored in .kibana indice.
indices, stored in ES, are not visible in kibana view, if not defined in kibana setting tabs.

access to these indices are controlled by RoR.
access to dashboard and vizu are controlled by kibana{group} indice.

I have no clue on how to catch kibana request to rewrite request to the right kibana indice. ( ex : catch .kibana to go to .kibana-secu , in all request)

**Comment by sscarduzio** [comment]
is this still needed?

**Comment by shubhamverma27** [comment]
@sscarduzio Well, Currently multi tenancy is done by launching multiple kibana instance ..
It would be great to have it in the same instance..
Somewhat Similar to kibana Own_Home 
You can add it in your future enhancements :)

**Comment by troupier** [comment]
Hello ! i've a similar problem (i think)

I've some groups of users which have their owns set of indices : group1 can't access group2 indices and so on.

The problem is that kibana have a mandatory default indice. 
If this default indice is positionned on group1-* indices and a group2 user access kibana :  
- first authentication (ok)
- a pop-up ask for the group2 to authenticate  again (as they haven't rights ont group1 indices)
-  this attempt will fail
- select the group2 indices pattern
- authenticate successfully and access group2 indices.

It's everything but userfriendly :)

I'd like to change the default indices pattern like the rewrite condition does from the user/group configuration.

Maybe it's something writed in the .kibana indice ?

Thank for your help

David

**Comment by ld57** [comment]
Hi @troupier ,

Here my strategy : 
- create an empty indice in es, named home
- create the pattern for home in kibana
- in kibana, define home pattern as default (the star)
- in RoR block of each group, add indice "home" to the indice array to authorize users to see it

When users from group 1 or 2 connect to kibana, they will get prompted for authentication 1 time, then they will reach home indice, with no data. 

Then users select in kibana indices on which they have rights, and no logon request will pop.

A logon request pop if users try to see in kibana unauthorized indices ( like your group B trying to see indices of group A)

Tell to user, if they did a mistake by selecting the wrong indice pattern in discover, and got logon pop, to just cancel the poped window, and then they can select again the good indices.
No more pop will happen, until they try to see that they can not :)

**Comment by troupier** [comment]
@ld57 thanks : works like a charm !
@sscarduzio thanks for the 1.16.8 , with the 5.5.0 release, i've something neat !  Great job !
