### ISSUE TITLE
Rules Documentation

### ISSUE THREAD

**Issue by trondhindenes** [sscarduzio/elasticsearch-readonlyrest-plugin#280]
I hate to be the guy who asks for better documentation, but I'm struggling to figure out the actual meaning of the various rule "Actions".
It would be awesome to have a list that maps elasticsearch api calls to the various rule actions. Right now I'm struggling with something as simple as giving a group "list indices" access, and I can't figure it out.

If ReadonlyRest's strategy is to charge for in-depth documentation, that's totally understandable but should maybe be called out.

**Comment by trondhindenes** [comment]
For example, the doc says:
"Every block must have at least the name and type fields."
However, there's tons of examples on the same page where the "type" field is omitted. We'd be interested in licensing readonlyrest, but first I need to be able to get it running - and for that my finding is that the current documentation lacks some detail.

**Comment by trondhindenes** [comment]
There's also mention of a kibana_access rule, but there's no actual description of how to implement it, nor any examples.

**Comment by sscarduzio** [comment]
>I hate to be the guy who asks for better documentation, but I'm struggling to figure out the actual meaning of the various rule "Actions".

I **love** to have somebody pointing out what's wrong and how to solve it. At all times, about anything.

>if ReadonlyRest's strategy is to charge for in-depth documentation, that's totally understandable but should maybe be called out.

That's ironic, because as a matter of fact ROR loses money from bad docs. 

> It would be awesome to have a list that maps elasticsearch api calls to the various rule actions. 

This is a difficult problem to solve, as Elastic doesn't give this kind of documentation (action names are somehow an internal thing). However, that doesn't mean there's nothing to be done.
The way X-Pack solved the problem is by grouping actions into [security privileges](https://www.elastic.co/guide/en/x-pack/5.6/security-privileges.html). We could work out something similar by associating the known list of actions (grepped from the ES codebase), to the same (or a subset) of the security privileges list they published. Then this would be a `privileges` macro rule.

> Right now I'm struggling with something as simple as giving a group "list indices" access, and I can't figure it out.

That's because you have to use the reverse approach:

- Have an ES instance with ROR installed and enabled (even without any ACL block, doesn't matter)
- Google how to list all the indices via the REST API (i.e. how to list all indices? (The cat API)
- launch the request via cURL or another REST client `curl http://localhost:9200/_cat/indices `
- read the ROR logs: i.e. `... TYP:ClusterStateRequest, CGR:N/A, USR:s(?), BRS:true, ACT:cluster:monitor/state, OA:127.0.0.1, IDX:, MET:GET, PTH:/_cat/indices?v, CNT:<N/A> ...`
- Take note of the action/method/path fields (ACT/MET/PTH) as it will be useful in your ACL rules creation process.

**Comment by sscarduzio** [comment]
You have a point about the lack of an example of kibana_access in the main docs. The only thing I found was an [example in the GitHub README.md](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin#use-case-multi-user-kibana--authenticated-logstash)

The reference to a mandatory `type` rule is gone. I explain this better now.

**Comment by trondhindenes** [comment]
The logs are a great help, but it's essentially "reverse-engineering" security and that just feels wrong to me. "see what fails and correct it" is (imho) not the way to implement strong and well-working ACLs.

That said, I totally get the daunting task of getting this documented, Elasticsearch is a complex thing. Still, as a fairly well-experienced guy when it comes to ES (I wrote something based on a similar idea as ReadOnlyRest as an excersise myself https://github.com/trondhindenes/WesternOmega) I'm still having problems getting readonlyrest access rules right.

**Comment by sscarduzio** [comment]
@trondhindenes I completely agree with you. I can see your have a fresher and more rational view to what ROR documentation should be than me: I've been too deep into the implementation details for too long. So I lost the user perspective, let alone the first time user perspective.

I'd love to see people like yourself and other users fixing some of the most evident woes of this documentation. Also, I believe an open source product should have open source documentation. 

So I moved everything into this new repo:

https://github.com/beshu-tech/readonlyrest-docs

* Small fixes welcome
* Rewording, sure!
* Paragraph restructuring, go ahead!
* Skeleton restructuring, no problem!

**Comment by trondhindenes** [comment]
Nice! I'll try and make some contributions there! Thanks!
