### ISSUE TITLE
ROR on cross-cluster searches

### ISSUE THREAD

**Issue by psaiz** [sscarduzio/elasticsearch-readonlyrest-plugin#306]
Hi Simone, 

I've been playing with the cross-cluster searches, and, unless I'm doing something wrong, it looks like they are not supported by the current version of ROR. The use case that I have is the following: 

1. I setup two clusters, A and B, following the documentation from [1]. Note that cluster A will connect to cluster B through the java api.  This means that ROR will be configured only on cluster A.
2. I would like to configure an user u1, who will have access to some indices of A and some indices from B. Ideally, I would put a rule like:

```yml
  - name: test_cross_cluster
    x_forwarded_for:
    - user1
    type: allow
    indices:
    - my_index_on_a*
    - b:another_index_on_b*
```

3. With that configuration, I would expect that the following queries work:
  curl -H 'x_forwarded_for: user1' http://a/my_index_on_a*/_search
  curl -H 'x_forwarded_for: user1' http://a/my*/_search
  curl -H 'x_forwarded_for: user1' http://a/b:another_index_on_b*/_search
  curl -H 'x_forwarded_for: user1' http://a/b:*/_search
  curl -H 'x_forwarded_for: user1' http://a/*:*/_search
4. I would expect also to get access denied going to things like
  curl -H 'x_forwarded_for: user1' http://a/another_index_on_b*/_search
  curl -H 'x_forwarded_for: user1' http://a/c*:*/_search
  curl -H 'x_forwarded_for: user1' http://a/b:different_index*/_search
  curl -H 'x_forwarded_for: user1' http://a/*:different_index*/_search

Does that make sense? Do you think that it will be possible to implement something similar?

Thanks a lot, 
pablo

[1] https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-cross-cluster-search.html

**Comment by sscarduzio** [comment]
Hi Pedro, thanks for formalising this. I've been working on it in the past couple of days, and I found both why it doesn't work now and how to make it work. But I have some doubt on the expected behaviour side.

## Why it didn't work
The current algorithm behind the indices rule has foundation on the fact that the local node knows the total list of indices and aliases in the local cluster.
Remote clusters' indices are not part of this list, and the algorithm fails.

## How I made it work
In the case remote clusters search feature is enabled in ES, and a ":" is detected in in the allowed indices, and the request is a SearchRequest, we use a different index replacement algorithm that attempts to do the same job of the current one, but operates **without knowing the list of indices**.

## Peculiarities about cross cluster search as a feature in ES (no ROR)

1. It applies exclusively to SearchRequest (to be verified if also _msearch)
2. When users request for a total search like `GET  http:/a/_search` or `GET http:/a/*/_search`, they just see local indices' results.
3. The cluster 'a' has no knowledge about the list of indices in cluster 'b' when it forwards the search.

## Decisions to be made for ROR
1. When we have `indices: ["b*"]` should we allow people to search for`b:idx1`?
2. When we have `indices: ["*"]` should we allow people to search for remote indices?
3. When we have `indices: ["a*", "b:*"]` and people request a total search,  should we return to results from cluster b?

**Comment by sscarduzio** [comment]
@psaiz can you give a try to  "zk_index_filter" branch?

**Comment by psaiz** [comment]
Hi Simone, 

Thanks for looking into this, and for the detailed explanation. Regarding the 'decisions to be made for ROR', I would recommend:
1. If we have indices b*, it should not be allow to search on b:*
2. No, the remote indices should only be done if the user puts the name of the cluster
3.Please, check what elasticsearch does. I have the felling that in the total searches it does not go through the remote clusters. ROR should behave in the same way

**Comment by sscarduzio** [comment]
@psaiz yep I confirm all above is what ROR should be doing right now in master branch
