### ISSUE TITLE
Index mapping creation issue

### ISSUE THREAD

**Issue by seanziee** [sscarduzio/elasticsearch-readonlyrest-plugin#317]
What action group is responsible for allow index pattern creation? Every time I want to create a new user, I sign in and I need to create a new index pattern but can't because the user has only kibana rw permissions. So in order to create a new user, I need to allow that user to have admin privileges, create index pattern, then go back to rw privileges. Am I missing something or is that what the normal flow is?

~~Update: I get this error when I try and create the index pattern even with admin perm. 
[2018-02-23T13:15:03,775][ERROR][t.b.r.e.RequestInfo      ] Found an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! IndexRequest~~

Kibana/ES 5.6.3

**Comment by seanziee** [comment]
I think I see what's happening. I have OwnHome in front of it and ROR isn't letting OwnHome create an index with the format .kibana_<username> so what's happening when the request fails is that I can't write to an index that doesn't exist. How can I allow OwnHome to create an index?

**Comment by seanziee** [comment]
For my second question, I made a stupid mistake by making the username with caps in it which causes an error from ES because it doesn't want caps in the name of indices. Now things are all good with my second question and that also allows me to create indices from OwnHome as well as with an admin user. But with a user with RO, what is the best method to add dashboards to that account?

**Comment by sscarduzio** [comment]
the workflow is that if someone has a read only customer, they need to put some dashboards for the customer to see in RO mode. And since creating the index pattern is a prerequisite to create dashboards, they will configure the index pattern for them as well in the same session.

Therefore, for each RO customer (tenant), I'm afraid there's no way around but to create a twin RW account for your customer (tenant) and configure it for them.

**Comment by seanziee** [comment]
Yeah that makes sense. Just wanted to confirm I wasn't missing something!
