### ISSUE TITLE
Support for older ES versions?

### ISSUE THREAD

**Issue by paolociccarese** [sscarduzio/elasticsearch-readonlyrest-plugin#32]
Simone, I am not sure that is of interest, but I have a version of the latest code base working with ES v.1.4.4. Something I had to do for some internal reasons. 

If that is of interest I can share it as well. I am not sure would be that helpful for anybody though.

**Comment by sscarduzio** [comment]
Many people have shown interest for 1.x compatible version of this plugin. That's why I keep a 1.x branch!
Have you seen it? However I saw it working down to 1.5.3, but didn't try with 1.4.
It would be nice if you could have a look there and fill some gaps if you find anything. 

And yes, I should advertise more about the availability of a 1.x branch.

**Comment by pciccarese** [comment]
I just looked at it now but I don't think that works for 1.4.4 as the process for the registration of Actions and Filters was different. The onModule call in the *Plugin main class was not working on 1.4.4 I believe. Or at least I was not able to get it to work :)

Your call, 1.4.4 would probably sit on yet another separate branch.

**Comment by sscarduzio** [comment]
Ok let's do this! How far backwards does this go?
We could publish builds for a few major pre-1.5 versions quite easily, I reckon.

It will be quite easy to support because the code is only slightly different.

I'll branch out the current master tomorrow so you'll be able to make a pull request against that.

**Comment by pciccarese** [comment]
I've tested only 1.4.4. I am assuming any 1.4.x will work. I cannot tell about versions previous to that one.

**Comment by sscarduzio** [comment]
No worries, I have this docker+newman based integration test system in place I can smoke-test a few versions and make some builds.

_S

**Comment by sscarduzio** [comment]
Hey @paolociccarese, I created a pre-1.5 branch, if you're still OK for that pull request? :)
