### ISSUE TITLE
ound an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! PercolateRequest

### ISSUE THREAD

**Issue by andresp99999** [sscarduzio/elasticsearch-readonlyrest-plugin#335]
I just noticed this error in our logs (reporting as requested).

[2018-04-14 17:56:45,334][ERROR][tech.beshu.ror.es.RequestInfo] Found an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! PercolateRequest

This is with ES 2.4.6 and readonlyrest  1.16.18

**Comment by sscarduzio** [comment]
Hi @andresp99999, this bug affects only ES 2.x, and is fixed now. You will find the fix in the next ROR version 1.16.19. Thanks for reporting. 

By the way the error is just a message, because everything should work via reflection as last resort case. It just prints the log line because handling via reflection is slower and all cases should be handled explicitly.
