### ISSUE TITLE
No attempt to authenticate against LDAP 

### ISSUE THREAD

**Issue by JKLS** [sscarduzio/elasticsearch-readonlyrest-plugin#394]
Disclaimer: First time posting a question so I apologize in advance if enough information isn't provided to give context.
Issue: When attempting to login into kibana there is no attempt being made to contact the ldap server i have configured via my elasticsearch.yml file. The file parses correctly and I am not getting any errors logged anywhere even when turning down the level to debug mode. I assume this is occurring because kibana doesn't know it should be contacting the ldap server via the elasticsearch master node but as there are no logs I am confused as to where I should begin looking to debug this issue. I have the same set up running of kibana and es on a different instance and it authenticates against the same LDAP server just fine, and I have also insured that both instances(the working and the non working one) can access the ldap server. Any guidance in resolving this issue would be greatly appreciated, also please let me know if more information is needed in order to assist.

**Comment by sscarduzio** [comment]
Hello @JKLS welcome to ReadonlyREST! A few comments:

1. What is your overall goal? Authenticated ES? Authenticated Kibana? With or without our Kibana plugins  [ROR PRO](http://readonlyrest.com/pro) / [ROR Enterprise](http://readonlyrest.com/enterprise)?

2. Generally, it's great if you could directly instruct us on how to reproduce the undesired behaviour by attaching the complete content of `readonlyrest.yml` (omitted secrets).

3. We highly discourage the use of `elasticsearch.yml` for storing ROR settings because the whole ACL and its secrets can easily leak via the Elasticsearch HTTP API.
