### ISSUE TITLE
Getting ready for 2.3.2

### ISSUE THREAD

**Issue by nasht00** [sscarduzio/elasticsearch-readonlyrest-plugin#54]
We are eagerly waiting for the release of ES 2.3.2 because of an issue which is a blocker for us (https://github.com/elastic/elasticsearch/issues/17483).

We also want to use your plugin, and I notice you create a different zip for each version of ES. Is this important? Will the plugin generated for 2.3.1 work with 2.3.2? Or do we need to wait for a new plugin before we can upgrade?

**Comment by sscarduzio** [comment]
Hi @nasht00, I release a new build every time because this is a java plugin and it uses Elastic Search internal API (also via reflection). That means it's pretty sensitive to internal changes. 

Not only this, there's another reason: in the past, you could install an old version of the plugin and it would work, but after ES 2.0 they made it mandatory to specify what ES version was the plugin built for, and the installation process **fails** if the version declared in the plugin manifest does not match exactly with the target ES version. So I can't really change this. :)

In principle though you can unzip the plugin and change the `plugin-descriptor.properties` file. But I don't recommend. I will give you a new build later today. No worries. Just ask and you'll have it :)

**Comment by nasht00** [comment]
Thanks

2.3.2 has not been released yet, so we'll just have to wait.
I'll ping you when they release it so we can start the process early.

**Comment by sscarduzio** [comment]
oh I see, cool just ping me when it's out. By the way I'm trying to find a way to be notified when a new ES release comes out. How do you do? Are you subscribed to some mailing list?

**Comment by nasht00** [comment]
I wish :)

I just look at their website and github account every day!

**Comment by sscarduzio** [comment]
@nasht00 
https://raw.githubusercontent.com/sscarduzio/elasticsearch-readonlyrest-plugin/v1.9/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip

**Comment by nasht00** [comment]
Thanks for the quick reaction! Will test it as soon as possible.

**Comment by sscarduzio** [comment]
Nice, let me know how it goes :)

**Comment by nasht00** [comment]
So far so good. No regression.

**Comment by sscarduzio** [comment]
Cool to know you're kicking this plugin's butt with some serious independent testing. This adds a lot of value/confidence to the project!

I'd actually love to know (if possible) what's the approach you guys took: use case, test scripts and overall considerations, conclusions. I.e.
- Are you testing in a multi node scenario?
- Is this performance, functional, or penetration testing?
- What features did you end up using most?

Thanks!

**Comment by nasht00** [comment]
We just started using elastic (and your plugin). Our usage is limited so far.  
We use it for the search box on this website: https://mobilefirstplatform.ibmcloud.com/

We have an internal script that index pages (bulk) and an external script that allows searching (just "view source" on our site). So we use your plugin to allow the public script from running while preventing any "write" access. We used the basic authentication `auth_key` feature.

We have a single node hosted as a Docker container on Bluemix.net, relatively low traffic, 722 documents as of today.

We did not perform any automated testing.
