### ISSUE TITLE
Document "<no_index>"

### ISSUE THREAD

**Issue by haizaar** [sscarduzio/elasticsearch-readonlyrest-plugin#61]
README.md file mentions "&lt;no_index&gt;" as part of indices configuration, however it's puzzling what it really does.

Thank you.

**Comment by sscarduzio** [comment]
Hello @haizaar,
Yes you have a point, didn't explain that well: `<no-index>` is a special string that matches the case no index has been detected in the request context. This is quite usual when clients request for generic cluster state related actions, for which the notion of indices-context simply does not apply.

In the example I have to include `<no-index>` because I have `cluster:*` among the allowed actions. If I omit it,  the rule won't match.

From the usability stand point, this is quite puzzling. But I believe the situation in which a system implicitly whitelists some stuff is not exactly the path of least surprise. Especially when you're defining ACLs for security.

Could you suggest a place where this lengthy explanation could live?

**Comment by haizaar** [comment]
Thanks for the info!

I would add the explanation below the examples in the README file. I've also posted your wording in the project wiki.

**Comment by sscarduzio** [comment]
Very well worded, thank you for adding it to the wiki! I will put a link to that paragraph in the readme 👍
