### ISSUE TITLE
How can I encrypt readonlyrest.yml?

### ISSUE THREAD

**Issue by dVp007** [sscarduzio/elasticsearch-readonlyrest-plugin#636]

**Comment by sscarduzio** [comment]
I have no context to understand if/where the encryption and decryption is supposed to take place, and if it makes sense or not, but one thing you could leverage would be replacing the entire content of readonlyrest.yml with an environmental variable. The variable can be encrypted/decrypted by some orchestration system.

```
$ export SOME_ENVIRONMENTAL_VAR_WITH_ALL_THE_CONTENT=".........."
$ cat readonlyrest.yml

${SOME_ENVIRONMENTAL_VAR_WITH_ALL_THE_CONTENT}

```
I hope this helps somehow, otherwise provide more context and more precise requirements
