### ISSUE TITLE
Ldap authentication

### ISSUE THREAD

**Issue by pdepaepe** [sscarduzio/elasticsearch-readonlyrest-plugin#66]
Hello,

May you please consider to support ldap binding?

Thanks

**Comment by sscarduzio** [comment]
Nice idea, this would add some dynamism to the otherwise static list of the available users. An LDAP server could be declared in the global configuration, the authentication result can be part of the RequestContext so then we could match blocks of rules for particular users.

**Comment by radoondas** [comment]
+1

**Comment by harveyzh** [comment]
+1

**Comment by nitram4** [comment]
+1

**Comment by ScriptAutomate** [comment]
+1

**Comment by TimCgn** [comment]
+1

**Comment by sscarduzio** [comment]
For whom may benefit, I documented how to run ES in IntelliJ with the plugin code hooked up.

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Development

**Comment by Vitiate** [comment]
+1

**Comment by TimCgn** [comment]
Ich kehre zurück am 04.08.2016.

Bei dringenden Anliegen wenden Sie sich bitte an meine Kollegen über den
Pallas Helpdesk (helpdesk@pallas.com, 02232-1896-94).

Mit freundlichen Grüßen
Tim Kretschmann

----
Dear Sir or Madam,

I am out of office. Your e-mail will not be forwarded. During my absence
our Pallas Helpdesk (helpdesk@pallas.com, 02232-1896-94) will help you to
get in touch with an alternative contact within our company. Thank you for
your patience.

Sincerely yours,
Tim Kretschmann



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[sscarduzio/elasticsearch-readonlyrest-plugin] Ldap authentication (#66)"
gesendet am 02.08.2016 22:26:02.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.


--------------------------------------------------------------------
//// pallas
Pallas GmbH / Hermülheimer Str. 8a / 50321 Brühl
Geschäftsführer: Stephan Sachweh
HR B 52019 Amtsgericht Köln
--------------------------------------------------------------------
Managed Service - Einfach sicher

**Comment by sscarduzio** [comment]
Hi Guys,
I hate to say: I could do it, but as it stands, literally does not make sense for me to continue developing this software.

I left my job and I'm creating a new (unrelated) product to sustain myself in the long run. Doing it while maintaining a security plugin is very tough because this requires a lot of time and attention.

And if I don't put all the work this plugin needs, we are all left with a half-assed security solution, which is the worse thing you could have.

Please read the Patreon campaign page: it's time to take this project to the next level or close it.

The only thing to add: as I always said, PRs are even better than donations. But in the absence of PRs, contributions are vital.

Best,

_Simone

**Comment by liff** [comment]
I would be interested in adding LDAP support to this plugin.

From the [comment](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/167#issuecomment-277979422) on #167 it looks like @coutoPL might be working on this already?

@coutoPL, are you working on it? If not, I could start tackling this pretty much right away. Otherwise, if you need assistance or want to coordinate efforts, let me know.

**Comment by coutoPL** [comment]
Hi @liff, yes I'm working on LDAP integration at the moment. I'm about to create PR. I'd like to add more tests, so it is a matter of day or two.

**Comment by liff** [comment]
Okay then, thanks.

**Comment by sscarduzio** [comment]
@coutoPL That's great, but I'd suggest don't write the tests yet, feel free to share more on what you are doing "as you go" so we can contribute with ideas etc. 
Just a OSS process suggestion :) What do you think?

**Comment by coutoPL** [comment]
sorry for delay. I found some time today and I've finished ldap support task. PR is here: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/180

**Comment by sscarduzio** [comment]
Thanks a lot @coutoPL! 
Wow this PR is huge! I agree the ES testing framework is like: all you wanted was a banana and you're given a gorilla holding a banana. 🍌🙈

I'll check out and review this PR ASAP after preparing the ground for it. Specifically, today I'm going  to:

- [ ] Sync all the latest bugfixes to all branches
- [ ] Move all the branches to Java 8 (this PR is the good excuse to abandon Java 7 support)
- [ ] Test a build for ES 5.1.2
- [ ] Release ReadonlyREST v1.13.2

And then check out, test and merge this PR. 
Once @coutoPL again thanks a lot for this, people were really screaming for this one!
