### ISSUE TITLE
Multiple Indexes

### ISSUE THREAD

**Issue by Christian1626** [sscarduzio/elasticsearch-readonlyrest-plugin#67]
Hello,
I have an index for each country(Mali,Madagascar): 
- logstash-canalv2-ml
- logstash-canalv2-mg

I created a metrics vizualiation that count the number of data. The vizualisation index is: **logstash-canalv2-***

Then I created a role for each country, to example for Mali.

```
- name: Mali
  auth_key: admin_ml:admin_ml
  kibana_access: ro+
  type: allow
  indices: ["<no-index>", ".kibana*", "logstash-canalv2-ml","default"]
```

And I would like when I'm connected with Mali role that I can only see its number of data and same thing for Madagascar.

But when I login with Mali and check the vizualisation it didn't work _"Visualize: Authentication Exception"_. I guess it's because my role not contains  **logstash-canalv2-*** but **logstash-canalv2-ml**.
So I don't know how to solve this :/. 

Sorry for my english, I hope you have understood my my issue.
Sincerely.

**Comment by sscarduzio** [comment]
Hey @Christian1626 this is a known limitation of this plugin. And there's out some design proposal on how to segregate the kibana dashboards on a per user basis. 
As a temporary fix, you could run multiple instances of kibana configured to use a custom index (instead of  the default `.kibana`) and configure a RO and a RW logins in readonly-rest plugin for each individual index.
Read more about `kibana_index` rule from the wiki: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules

**Comment by sscarduzio** [comment]
See #62

**Comment by Christian1626** [comment]
Ok, thanks for your answer.
