### ISSUE TITLE
请问配置更新有api吗？

### ISSUE THREAD

**Issue by huangpeng0817** [sscarduzio/elasticsearch-readonlyrest-plugin#768]
请问插件安装后，后续有更新规则，例如开启了集群访问ip控制，后续需要更新ip列表，支持api动态更新吗？还是只能修改yml配置文件，然后重启节点生效？

**Comment by coutoPL** [comment]
Hi @huangpeng0817,

ROR Pro has a feature called the Clusterwide Settings (see [here](https://readonlyrest.com/pro/)) which is sth what you probably need. No node restart is required in this method.

**Comment by huangpeng0817** [comment]
> Hi @huangpeng0817,
> 
> ROR Pro has a feature called the Clusterwide Settings (see [here](https://readonlyrest.com/pro/)) which is sth what you probably need. No node restart is required in this method.

@coutoPL 
 好吧。以为这个修改配置不需要重启节点是开源功能。如果是收费的话，直接使用x-pack即可。因为都需要购买授权。如果可以，希望可以开放动态更新配置的api接口。

**Comment by sscarduzio** [comment]
The problem is not the openness of the API, the problem is the guarantee on the stability of the settings API. For example, at the moment we are planning on expanding our PRO and Enterprise plugins settings editor GUI capabilities with temporary settings, impersonation, mock authentication services. And most likely this API will need to change.

And  by the way, @huangpeng0817, as far as I know, purchasing x-pack will cost you 10x ROR PRO. So, if your company uses our open source technology, sponsoring us with purchasing an entry level license would make sense in your best interest (think of what we can learn from the log4j security vulnerability issue).
